version: 2
jobs:
  build:
    machine: true
  steps:
    - checkout
    - run: 
      name: Build Image
      command: |
      docker info
      docker build -t jonarnaldo:movies_be
    - run:
      name: Add Image to docker heroku repository
      command: |
      docker login -username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
      docker tag jonarnaldo:movies_be registry.heroku.com/$HEROKU_APP_NAME/web
      docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - run:
      name: Setup Heroku
      command: |
        chmod +x .circleci/setup-heroku.sh
        .circleci/setup-heroku.sh
    - run:
      name: Deploy to Heroku
      command: |
        heroku container:release web --app $HEROKU_APP_NAME
